import { StoryType, ImageStyle, ImageMode, Voice } from '../types';

export const STORY_TYPES: StoryType[] = [
  {
    id: 'scary_horror',
    name: 'Scary Horror',
    icon: '👻',
    description: 'Terrifying tales that keep viewers on edge',
    bestFor: 'Suspense, fear, supernatural',
  },
  {
    id: 'emotional_heartwarming',
    name: 'Emotional Heartwarming',
    icon: '❤️',
    description: 'Touch hearts with inspiring human stories',
    bestFor: 'Family, friendship, love',
  },
  {
    id: 'true_crime',
    name: 'True Crime',
    icon: '🔍',
    description: 'Real-life mysteries and investigations',
    bestFor: 'Documentary, investigation, mystery',
  },
  {
    id: 'anime_style',
    name: 'Anime Style',
    icon: '🎌',
    description: 'Dynamic Japanese animation narratives',
    bestFor: 'Action, adventure, fantasy',
  },
  {
    id: 'historical_documentary',
    name: 'Historical Documentary',
    icon: '📚',
    description: 'Educational stories from the past',
    bestFor: 'History, education, biography',
  },
  {
    id: 'surprising_twist',
    name: 'Surprising Twist',
    icon: '🎭',
    description: 'Unexpected endings that shock viewers',
    bestFor: 'Mystery, thriller, drama',
  },
  {
    id: 'motivational_inspiring',
    name: 'Motivational Inspiring',
    icon: '💪',
    description: 'Empower and motivate your audience',
    bestFor: 'Success, self-help, achievement',
  },
  {
    id: 'mystery_thriller',
    name: 'Mystery Thriller',
    icon: '🕵️',
    description: 'Keep viewers guessing until the end',
    bestFor: 'Detective, puzzle, suspense',
  },
  {
    id: 'war_military',
    name: 'War & Military',
    icon: '⚔️',
    description: 'Heroic tales from the battlefield',
    bestFor: 'Action, history, heroism',
  },
  {
    id: 'nature_wildlife',
    name: 'Nature & Wildlife',
    icon: '🦁',
    description: 'David Attenborough-style documentaries',
    bestFor: 'Animals, environment, science',
  },
  {
    id: 'comedy_funny',
    name: 'Comedy & Funny',
    icon: '😂',
    description: 'Entertaining and humorous stories',
    bestFor: 'Entertainment, satire, parody',
  },
  {
    id: 'romantic_love',
    name: 'Romantic Love',
    icon: '💑',
    description: 'Beautiful love stories and relationships',
    bestFor: 'Romance, drama, emotions',
  },
  {
    id: 'scifi_future',
    name: 'Sci-Fi Future',
    icon: '🚀',
    description: 'Futuristic and technological narratives',
    bestFor: 'Space, technology, future',
  },
  {
    id: 'fantasy_epic',
    name: 'Fantasy Epic',
    icon: '⚔️',
    description: 'Magical worlds and epic adventures',
    bestFor: 'Magic, dragons, mythology',
  },
  {
    id: 'biographical',
    name: 'Biographical',
    icon: '📖',
    description: 'Real-life stories of remarkable people',
    bestFor: 'History, inspiration, education',
  },
  {
    id: 'conspiracy',
    name: 'Conspiracy',
    icon: '🕵️',
    description: 'Uncover hidden truths and secrets',
    bestFor: 'Mystery, investigation, thriller',
  },
  {
    id: 'psychological',
    name: 'Psychological',
    icon: '🧠',
    description: 'Mind-bending psychological narratives',
    bestFor: 'Thriller, horror, drama',
  },
  {
    id: 'adventure_survival',
    name: 'Adventure Survival',
    icon: '🏔️',
    description: 'Extreme survival and adventure stories',
    bestFor: 'Action, nature, survival',
  },
  {
    id: 'paranormal',
    name: 'Paranormal',
    icon: '👻',
    description: 'Supernatural and unexplained phenomena',
    bestFor: 'Mystery, horror, supernatural',
  },
  {
    id: 'documentary_real',
    name: 'Documentary Real',
    icon: '🎬',
    description: 'Authentic real-world stories',
    bestFor: 'Education, news, real events',
  },
];

export const IMAGE_STYLES: ImageStyle[] = [
  {
    id: 'cinematic',
    name: 'Cinematic Film',
    icon: '🎬',
    description: 'Movie-quality production',
    preview: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
  {
    id: 'documentary',
    name: 'Documentary Real',
    icon: '📹',
    description: 'National Geographic style',
    preview: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
  },
  {
    id: 'anime',
    name: 'Anime Style',
    icon: '🎌',
    description: 'Professional Japanese animation',
    preview: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
  },
  {
    id: 'horror',
    name: 'Horror Creepy',
    icon: '👻',
    description: 'Dark, terrifying atmosphere',
    preview: 'linear-gradient(135deg, #434343 0%, #000000 100%)',
  },
  {
    id: 'comic',
    name: 'Comic Book',
    icon: '📚',
    description: 'Graphic novel illustration',
    preview: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
  },
  {
    id: 'historical',
    name: 'Historical Photo',
    icon: '📸',
    description: 'Vintage, sepia photography',
    preview: 'linear-gradient(135deg, #d4a574 0%, #8b7355 100%)',
  },
  {
    id: 'scifi',
    name: 'Sci-Fi Future',
    icon: '🚀',
    description: 'Cyberpunk, neon, futuristic',
    preview: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
  {
    id: 'noir',
    name: 'Dark Noir',
    icon: '🌑',
    description: 'High contrast, film noir',
    preview: 'linear-gradient(135deg, #4b4b4b 0%, #1a1a1a 100%)',
  },
  {
    id: 'fantasy',
    name: 'Fantasy Epic',
    icon: '⚔️',
    description: 'Magical, epic fantasy art',
    preview: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
  },
  {
    id: '3d_render',
    name: '3D Render',
    icon: '🎮',
    description: 'Photorealistic 3D graphics',
    preview: 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)',
  },
  {
    id: 'sketch',
    name: 'Sketch Drawing',
    icon: '✏️',
    description: 'Hand-drawn pencil art',
    preview: 'linear-gradient(135deg, #e0e0e0 0%, #b0b0b0 100%)',
  },
  {
    id: 'watercolor',
    name: 'Watercolor',
    icon: '🎨',
    description: 'Soft watercolor painting',
    preview: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
  },
  {
    id: 'oil_painting',
    name: 'Oil Painting',
    icon: '🖼️',
    description: 'Classical art style',
    preview: 'linear-gradient(135deg, #ff9a56 0%, #ff6a88 100%)',
  },
  {
    id: 'retro',
    name: 'Retro Vintage',
    icon: '📻',
    description: '1970s-1980s aesthetic',
    preview: 'linear-gradient(135deg, #fbc2eb 0%, #a6c1ee 100%)',
  },
];

export const IMAGE_MODES: ImageMode[] = [
  {
    id: 'ai_only',
    name: 'AI Only',
    icon: '🤖',
    description: 'Fully automated AI image generation',
    features: [
      'System generates all images automatically',
      'Uses Pollinations AI (free, unlimited)',
      'Character consistency maintained',
      'Processing time: ~30-60 seconds',
    ],
    bestFor: 'Quick generation, consistent style',
  },
  {
    id: 'manual_only',
    name: 'Manual Only',
    icon: '👤',
    description: 'Upload your own images',
    features: [
      'You provide all images',
      'Upload section appears below',
      'Full control over visuals',
      'Accepts: PNG, JPG, WEBP',
    ],
    bestFor: 'Custom artwork, specific visuals',
  },
  {
    id: 'stock_only',
    name: 'Stock Only',
    icon: '📹',
    description: 'Professional stock media from Pexels',
    features: [
      'Downloads videos and images',
      'Keyword search enabled',
      'Mix of video clips and photos',
      'Processing time: ~2-5 minutes',
    ],
    bestFor: 'Realistic, professional footage',
  },
  {
    id: 'ai_manual',
    name: 'AI + Manual Mix',
    icon: '🔄',
    description: 'Combine AI generation with your images',
    features: ['50% AI generated', '50% your uploads', 'Best of both worlds'],
    bestFor: 'Partial custom control',
  },
  {
    id: 'ai_stock',
    name: 'AI + Stock Mix',
    icon: '🔄',
    description: 'Blend AI images with stock media',
    features: [
      'AI generated scenes',
      'Stock footage for realism',
      'Dynamic combination',
    ],
    bestFor: 'Professional + creative',
  },
  {
    id: 'manual_stock',
    name: 'Manual + Stock Mix',
    icon: '🔄',
    description: 'Your images + stock media',
    features: [
      'Custom images',
      'Professional stock clips',
      'Hybrid approach',
    ],
    bestFor: 'Personal + professional',
  },
  {
    id: 'all_mix',
    name: 'All Three Mix',
    icon: '🔄',
    description: 'Ultimate combination',
    features: [
      'AI generated images',
      'Your custom uploads',
      'Professional stock media',
      'Maximum variety',
    ],
    bestFor: 'Maximum quality and variety',
  },
];

// ═══════════════════════════════════════════════════════════════
// ✅ UPDATED VOICES - KOKORO TTS + EDGE-TTS
// ═══════════════════════════════════════════════════════════════

export const VOICES: Voice[] = [
  // ───────────────────────────────────────────────────────────
  // KOKORO TTS - AMERICAN FEMALE (11 voices)
  // ───────────────────────────────────────────────────────────
  {
    id: 'af_bella',
    name: 'Bella (Female)',
    icon: '👩',
    description: 'Warm, engaging, natural',
    accent: 'American',
    engine: 'kokoro',
    bestFor: 'Emotional, Heartwarming, Nature',
    tone: 'Warm, friendly',
  },
  {
    id: 'af_nova',
    name: 'Nova (Female)',
    icon: '⭐',
    description: 'Energetic, dynamic, powerful',
    accent: 'American',
    engine: 'kokoro',
    bestFor: 'Action, Fantasy, Adventure',
    tone: 'Energetic, exciting',
  },
  {
    id: 'af_sarah',
    name: 'Sarah (Female)',
    icon: '📚',
    description: 'Professional, clear, authoritative',
    accent: 'American',
    engine: 'kokoro',
    bestFor: 'Documentary, True Crime, History',
    tone: 'Professional, confident',
  },
  {
    id: 'af_nicole',
    name: 'Nicole (Female)',
    icon: '💫',
    description: 'Smooth, sophisticated, elegant',
    accent: 'American',
    engine: 'kokoro',
    bestFor: 'Romance, Luxury, Sophisticated',
    tone: 'Smooth, elegant',
  },
  {
    id: 'af_jessica',
    name: 'Jessica (Female)',
    icon: '🎯',
    description: 'Sharp, direct, confident',
    accent: 'American',
    engine: 'kokoro',
    bestFor: 'Thriller, Mystery, Action',
    tone: 'Direct, intense',
  },
  {
    id: 'af_river',
    name: 'River (Female)',
    icon: '🌊',
    description: 'Calm, soothing, peaceful',
    accent: 'American',
    engine: 'kokoro',
    bestFor: 'Meditation, Nature, Calm',
    tone: 'Soft, soothing',
  },
  {
    id: 'af_sky',
    name: 'Sky (Female)',
    icon: '☁️',
    description: 'Dreamy, ethereal, whimsical',
    accent: 'American',
    engine: 'kokoro',
    bestFor: 'Fantasy, Dream, Magical',
    tone: 'Dreamy, ethereal',
  },
  {
    id: 'af_heart',
    name: 'Heart (Female)',
    icon: '💕',
    description: 'Sweet, caring, emotional',
    accent: 'American',
    engine: 'kokoro',
    bestFor: 'Emotional, Love, Family',
    tone: 'Sweet, caring',
  },
  {
    id: 'af_kore',
    name: 'Kore (Female)',
    icon: '🎨',
    description: 'Artistic, creative, expressive',
    accent: 'American',
    engine: 'kokoro',
    bestFor: 'Creative, Art, Educational',
    tone: 'Expressive, creative',
  },
  {
    id: 'af_aoede',
    name: 'Aoede (Female)',
    icon: '🎵',
    description: 'Musical, lyrical, poetic',
    accent: 'American',
    engine: 'kokoro',
    bestFor: 'Poetry, Music, Artistic',
    tone: 'Lyrical, poetic',
  },
  {
    id: 'af_alloy',
    name: 'Alloy (Female)',
    icon: '🔮',
    description: 'Mysterious, mystical, deep',
    accent: 'American',
    engine: 'kokoro',
    bestFor: 'Horror, Mystery, Paranormal',
    tone: 'Mysterious, deep',
  },

  // ───────────────────────────────────────────────────────────
  // KOKORO TTS - AMERICAN MALE (2 voices)
  // ───────────────────────────────────────────────────────────
  {
    id: 'am_adam',
    name: 'Adam (Male)',
    icon: '🎙️',
    description: 'Deep, authoritative, dramatic',
    accent: 'American',
    engine: 'kokoro',
    bestFor: 'Horror, True Crime, Mystery',
    tone: 'Deep, dramatic',
  },
  {
    id: 'am_michael',
    name: 'Michael (Male)',
    icon: '👔',
    description: 'Professional, clear, trustworthy',
    accent: 'American',
    engine: 'kokoro',
    bestFor: 'Documentary, Business, News',
    tone: 'Professional, clear',
  },

  // ───────────────────────────────────────────────────────────
  // KOKORO TTS - BRITISH (4 voices)
  // ───────────────────────────────────────────────────────────
  {
    id: 'bf_emma',
    name: 'Emma (British Female)',
    icon: '🇬🇧👩',
    description: 'Sophisticated British female',
    accent: 'British',
    engine: 'kokoro',
    bestFor: 'Nature, History, Documentary',
    tone: 'Sophisticated, refined',
  },
  {
    id: 'bf_isabella',
    name: 'Isabella (British Female)',
    icon: '🇬🇧✨',
    description: 'Elegant British female',
    accent: 'British',
    engine: 'kokoro',
    bestFor: 'Romance, History, Fantasy',
    tone: 'Elegant, refined',
  },
  {
    id: 'bm_george',
    name: 'George (British Male)',
    icon: '🇬🇧🎙️',
    description: 'David Attenborough style',
    accent: 'British',
    engine: 'kokoro',
    bestFor: 'Nature, Documentary, Epic',
    tone: 'Authoritative, epic',
  },
  {
    id: 'bm_lewis',
    name: 'Lewis (British Male)',
    icon: '🇬🇧👔',
    description: 'Confident British male',
    accent: 'British',
    engine: 'kokoro',
    bestFor: 'History, Biography, News',
    tone: 'Confident, authoritative',
  },

  // ───────────────────────────────────────────────────────────
  // EDGE-TTS - FALLBACK OPTIONS (3 voices)
  // ───────────────────────────────────────────────────────────
  {
    id: 'en-US-GuyNeural',
    name: 'Guy (Edge - Fallback)',
    icon: '🔄',
    description: 'Default male voice (backup)',
    accent: 'American',
    engine: 'edge',
    bestFor: 'Quick fallback',
    tone: 'Clear, neutral',
  },
  {
    id: 'en-US-AriaNeural',
    name: 'Aria (Edge - Fallback)',
    icon: '🔄',
    description: 'Default female voice (backup)',
    accent: 'American',
    engine: 'edge',
    bestFor: 'Quick fallback',
    tone: 'Clear, natural',
  },
  {
    id: 'en-US-JennyNeural',
    name: 'Jenny (Edge - Fallback)',
    icon: '🔄',
    description: 'Young female voice (backup)',
    accent: 'American',
    engine: 'edge',
    bestFor: 'Quick fallback',
    tone: 'Young, energetic',
  },
];

export const HOOK_INTENSITIES = [
  { value: 'mild', label: 'Gentle Opening - Slow build-up' },
  { value: 'medium', label: 'Strong Opening - Clear intrigue' },
  { value: 'extreme', label: 'EXPLOSIVE Opening - Immediate action' },
];

export const PACING_STYLES = [
  { value: 'slow', label: 'Atmospheric - Long, detailed sentences' },
  { value: 'medium', label: 'Balanced - Steady progression' },
  { value: 'dynamic', label: 'Varied - Mix of fast and slow' },
  { value: 'fast', label: 'Rapid Fire - Short, punchy sentences' },
];

export const DURATION_LABELS = [
  { min: 1, max: 5, label: 'Quick' },
  { min: 6, max: 15, label: 'Medium' },
  { min: 16, max: 30, label: 'Long' },
  { min: 31, max: 60, label: 'Epic' },
];