import { StoryType, ImageStyle, ImageMode, Voice } from '../types';

export const STORY_TYPES: StoryType[] = [
  {
    id: 'scary_horror',
    name: 'Scary Horror',
    icon: '👻',
    description: 'Terrifying tales that keep viewers on edge',
    bestFor: 'Suspense, fear, supernatural',
  },
  {
    id: 'emotional_heartwarming',
    name: 'Emotional Heartwarming',
    icon: '❤️',
    description: 'Touch hearts with inspiring human stories',
    bestFor: 'Family, friendship, love',
  },
  {
    id: 'true_crime',
    name: 'True Crime',
    icon: '🔍',
    description: 'Real-life mysteries and investigations',
    bestFor: 'Documentary, investigation, mystery',
  },
  {
    id: 'anime_style',
    name: 'Anime Style',
    icon: '🎌',
    description: 'Dynamic Japanese animation narratives',
    bestFor: 'Action, adventure, fantasy',
  },
  {
    id: 'historical_documentary',
    name: 'Historical Documentary',
    icon: '📚',
    description: 'Educational stories from the past',
    bestFor: 'History, education, biography',
  },
  {
    id: 'surprising_twist',
    name: 'Surprising Twist',
    icon: '🎭',
    description: 'Unexpected endings that shock viewers',
    bestFor: 'Mystery, thriller, drama',
  },
  {
    id: 'motivational_inspiring',
    name: 'Motivational Inspiring',
    icon: '💪',
    description: 'Empower and motivate your audience',
    bestFor: 'Success, self-help, achievement',
  },
  {
    id: 'mystery_thriller',
    name: 'Mystery Thriller',
    icon: '🕵️',
    description: 'Keep viewers guessing until the end',
    bestFor: 'Detective, puzzle, suspense',
  },
  {
    id: 'war_military',
    name: 'War & Military',
    icon: '⚔️',
    description: 'Heroic tales from the battlefield',
    bestFor: 'Action, history, heroism',
  },
  {
    id: 'nature_wildlife',
    name: 'Nature & Wildlife',
    icon: '🦁',
    description: 'David Attenborough-style documentaries',
    bestFor: 'Animals, environment, science',
  },
  {
    id: 'comedy_funny',
    name: 'Comedy & Funny',
    icon: '😂',
    description: 'Entertaining and humorous stories',
    bestFor: 'Entertainment, satire, parody',
  },
  {
    id: 'romantic_love',
    name: 'Romantic Love',
    icon: '💑',
    description: 'Beautiful love stories and relationships',
    bestFor: 'Romance, drama, emotions',
  },
  {
    id: 'scifi_future',
    name: 'Sci-Fi Future',
    icon: '🚀',
    description: 'Futuristic and technological narratives',
    bestFor: 'Space, technology, future',
  },
  {
    id: 'fantasy_epic',
    name: 'Fantasy Epic',
    icon: '⚔️',
    description: 'Magical worlds and epic adventures',
    bestFor: 'Magic, dragons, mythology',
  },
  {
    id: 'biographical',
    name: 'Biographical',
    icon: '📖',
    description: 'Real-life stories of remarkable people',
    bestFor: 'History, inspiration, education',
  },
  {
    id: 'conspiracy',
    name: 'Conspiracy',
    icon: '🕵️',
    description: 'Uncover hidden truths and secrets',
    bestFor: 'Mystery, investigation, thriller',
  },
  {
    id: 'psychological',
    name: 'Psychological',
    icon: '🧠',
    description: 'Mind-bending psychological narratives',
    bestFor: 'Thriller, horror, drama',
  },
  {
    id: 'adventure_survival',
    name: 'Adventure Survival',
    icon: '🏔️',
    description: 'Extreme survival and adventure stories',
    bestFor: 'Action, nature, survival',
  },
  {
    id: 'paranormal',
    name: 'Paranormal',
    icon: '👻',
    description: 'Supernatural and unexplained phenomena',
    bestFor: 'Mystery, horror, supernatural',
  },
  {
    id: 'documentary_real',
    name: 'Documentary Real',
    icon: '🎬',
    description: 'Authentic real-world stories',
    bestFor: 'Education, news, real events',
  },
];

export const IMAGE_STYLES: ImageStyle[] = [
  {
    id: 'cinematic',
    name: 'Cinematic Film',
    icon: '🎬',
    description: 'Movie-quality production',
    preview: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
  {
    id: 'documentary',
    name: 'Documentary Real',
    icon: '📹',
    description: 'National Geographic style',
    preview: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
  },
  {
    id: 'anime',
    name: 'Anime Style',
    icon: '🎌',
    description: 'Professional Japanese animation',
    preview: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
  },
  {
    id: 'horror',
    name: 'Horror Creepy',
    icon: '👻',
    description: 'Dark, terrifying atmosphere',
    preview: 'linear-gradient(135deg, #434343 0%, #000000 100%)',
  },
  {
    id: 'comic',
    name: 'Comic Book',
    icon: '📚',
    description: 'Graphic novel illustration',
    preview: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
  },
  {
    id: 'historical',
    name: 'Historical Photo',
    icon: '📸',
    description: 'Vintage, sepia photography',
    preview: 'linear-gradient(135deg, #d4a574 0%, #8b7355 100%)',
  },
  {
    id: 'scifi',
    name: 'Sci-Fi Future',
    icon: '🚀',
    description: 'Cyberpunk, neon, futuristic',
    preview: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
  {
    id: 'noir',
    name: 'Dark Noir',
    icon: '🌑',
    description: 'High contrast, film noir',
    preview: 'linear-gradient(135deg, #4b4b4b 0%, #1a1a1a 100%)',
  },
  {
    id: 'fantasy',
    name: 'Fantasy Epic',
    icon: '⚔️',
    description: 'Magical, epic fantasy art',
    preview: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
  },
  {
    id: '3d_render',
    name: '3D Render',
    icon: '🎮',
    description: 'Photorealistic 3D graphics',
    preview: 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)',
  },
  {
    id: 'sketch',
    name: 'Sketch Drawing',
    icon: '✏️',
    description: 'Hand-drawn pencil art',
    preview: 'linear-gradient(135deg, #e0e0e0 0%, #b0b0b0 100%)',
  },
  {
    id: 'watercolor',
    name: 'Watercolor',
    icon: '🎨',
    description: 'Soft watercolor painting',
    preview: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
  },
  {
    id: 'oil_painting',
    name: 'Oil Painting',
    icon: '🖼️',
    description: 'Classical art style',
    preview: 'linear-gradient(135deg, #ff9a56 0%, #ff6a88 100%)',
  },
  {
    id: 'retro',
    name: 'Retro Vintage',
    icon: '📻',
    description: '1970s-1980s aesthetic',
    preview: 'linear-gradient(135deg, #fbc2eb 0%, #a6c1ee 100%)',
  },
];

export const IMAGE_MODES: ImageMode[] = [
  {
    id: 'ai_only',
    name: 'AI Only',
    icon: '🤖',
    description: 'Fully automated AI image generation',
    features: [
      'System generates all images automatically',
      'Uses Pollinations AI (free, unlimited)',
      'Character consistency maintained',
      'Processing time: ~30-60 seconds',
    ],
    bestFor: 'Quick generation, consistent style',
  },
  {
    id: 'manual_only',
    name: 'Manual Only',
    icon: '👤',
    description: 'Upload your own images',
    features: [
      'You provide all images',
      'Upload section appears below',
      'Full control over visuals',
      'Accepts: PNG, JPG, WEBP',
    ],
    bestFor: 'Custom artwork, specific visuals',
  },
  {
    id: 'stock_only',
    name: 'Stock Only',
    icon: '📹',
    description: 'Professional stock media from Pexels',
    features: [
      'Downloads videos and images',
      'Keyword search enabled',
      'Mix of video clips and photos',
      'Processing time: ~2-5 minutes',
    ],
    bestFor: 'Realistic, professional footage',
  },
  {
    id: 'ai_manual',
    name: 'AI + Manual Mix',
    icon: '🔄',
    description: 'Combine AI generation with your images',
    features: ['50% AI generated', '50% your uploads', 'Best of both worlds'],
    bestFor: 'Partial custom control',
  },
  {
    id: 'ai_stock',
    name: 'AI + Stock Mix',
    icon: '🔄',
    description: 'Blend AI images with stock media',
    features: [
      'AI generated scenes',
      'Stock footage for realism',
      'Dynamic combination',
    ],
    bestFor: 'Professional + creative',
  },
  {
    id: 'manual_stock',
    name: 'Manual + Stock Mix',
    icon: '🔄',
    description: 'Your images + stock media',
    features: [
      'Custom images',
      'Professional stock clips',
      'Hybrid approach',
    ],
    bestFor: 'Personal + professional',
  },
  {
    id: 'all_mix',
    name: 'All Three Mix',
    icon: '🔄',
    description: 'Ultimate combination',
    features: [
      'AI generated images',
      'Your custom uploads',
      'Professional stock media',
      'Maximum variety',
    ],
    bestFor: 'Maximum quality and variety',
  },
];

// ═══════════════════════════════════════════════════════════════
// ✅ EDGE-TTS VOICES
// ═══════════════════════════════════════════════════════════════

export const VOICES: Voice[] = [
  {
    id: 'male_narrator_deep',
    name: 'Guy (Deep Male)',
    icon: '🎙️',
    description: 'Deep, cinematic narrator with a dramatic presence.',
    accent: 'American',
    engine: 'edge',
    bestFor: 'Horror, documentaries, epic trailers',
    tone: 'Deep, resonant',
  },
  {
    id: 'male_narrator_calm',
    name: 'Christopher (Calm Male)',
    icon: '🧠',
    description: 'Thoughtful and steady storyteller for educational content.',
    accent: 'American',
    engine: 'edge',
    bestFor: 'Educational, explainers, documentaries',
    tone: 'Calm, reassuring',
  },
  {
    id: 'male_narrator_dramatic',
    name: 'Davis (Dramatic Male)',
    icon: '🔥',
    description: 'Powerful voice that adds intensity and urgency.',
    accent: 'American',
    engine: 'edge',
    bestFor: 'Thrillers, sports, suspense',
    tone: 'Intense, powerful',
  },
  {
    id: 'female_narrator',
    name: 'Aria (Warm Female)',
    icon: '🎵',
    description: 'Professional narrator with a warm, engaging delivery.',
    accent: 'American',
    engine: 'edge',
    bestFor: 'Lifestyle, tutorials, professional content',
    tone: 'Warm, clear',
  },
  {
    id: 'female_narrator_warm',
    name: 'Sara (Compassionate Female)',
    icon: '💖',
    description: 'Comforting storyteller that feels personal and heartfelt.',
    accent: 'American',
    engine: 'edge',
    bestFor: 'Inspiration, wellness, testimonials',
    tone: 'Compassionate, warm',
  },
  {
    id: 'female_young',
    name: 'Jenny (Energetic Female)',
    icon: '🌟',
    description: 'Bright and modern narrator perfect for upbeat videos.',
    accent: 'American',
    engine: 'edge',
    bestFor: 'YouTube, ads, youth content',
    tone: 'Energetic, friendly',
  },
  {
    id: 'female_storyteller',
    name: 'Libby (British Storyteller)',
    icon: '🇬🇧✨',
    description: 'Elegant British voice with a warm storytelling style.',
    accent: 'British',
    engine: 'edge',
    bestFor: 'Fantasy, history, documentaries',
    tone: 'Elegant, expressive',
  },
  {
    id: 'narrator_british_female',
    name: 'Sonia (British Female)',
    icon: '🇬🇧',
    description: 'Polished and sophisticated British narrator.',
    accent: 'British',
    engine: 'edge',
    bestFor: 'Luxury, narration, storytelling',
    tone: 'Refined, smooth',
  },
  {
    id: 'narrator_british_male',
    name: 'Ryan (British Male)',
    icon: '🎩',
    description: 'Classic British narrator ideal for documentaries.',
    accent: 'British',
    engine: 'edge',
    bestFor: 'Documentaries, nature, mystery',
    tone: 'Authoritative, calm',
  },
];

export const HOOK_INTENSITIES = [
  { value: 'mild', label: 'Gentle Opening - Slow build-up' },
  { value: 'medium', label: 'Strong Opening - Clear intrigue' },
  { value: 'extreme', label: 'EXPLOSIVE Opening - Immediate action' },
];

export const PACING_STYLES = [
  { value: 'slow', label: 'Atmospheric - Long, detailed sentences' },
  { value: 'medium', label: 'Balanced - Steady progression' },
  { value: 'dynamic', label: 'Varied - Mix of fast and slow' },
  { value: 'fast', label: 'Rapid Fire - Short, punchy sentences' },
];

export const DURATION_LABELS = [
  { min: 1, max: 5, label: 'Quick' },
  { min: 6, max: 15, label: 'Medium' },
  { min: 16, max: 30, label: 'Long' },
  { min: 31, max: 60, label: 'Epic' },
];